### ISSUE TITLE
Install doc suggestion?

### ISSUE THREAD

**Issue by skoczen** [codysoyland/django-smart-load-tag#1]
Hey, thanks for writing this - it makes my life _much_ easier.

One minor suggestion on the docs - throwing a quick install section, that does the 'put it in installed apps', and 'here's how to include it by default' stuff, ie:

urls.py

```
from django.template import add_to_builtins
add_to_builtins('smart_load_tag.templatetags.smart_load')
```

Would be happy to make a pull request to save you the time if you'd like!

Thanks again.

**Comment by codysoyland** [comment]
Thanks for the note! I added an installation section to the readme. Please let me know if I should add more.

**Comment by skoczen** [comment]
Looks great by me - thanks again!
