### ISSUE TITLE
pip install django-smart-load-tag fails

### ISSUE THREAD

**Issue by aiiie** [codysoyland/django-smart-load-tag#2]
With an error like this:

```
IOError: [Errno 2] No such file or directory: 'build/django-smart-load-tag/README.rst'
```

You need a MANIFEST.in file that includes README.rst. You should probably also include LICENSE and tests/. Otherwise those files won't be included in the tarball that's upload to PyPI (the one generated by ./setup.py sdist).

**Comment by codysoyland** [comment]
Thanks for the note. I added the MANIFEST.in and pushed a new release to pypi.
