### ISSUE TITLE
ERROR: "too many values to unpack "

### ISSUE THREAD

**Issue by hsparikh** [codysoyland/django-smart-load-tag#4]
I am trying to import a thumbnail tag from a third party app called sorl, located at sorl.thumbnail.templatetags.thumbnail, and I keep on getting the error: "too many values to unpack". It excepts out at C:\Python27\lib\site-packages\smart_load_tag\templatetags\smart_load.py in parse_lib_tag, line 44

Any insight into what the problem is that is causing this issue? I tried both load and import tags.

**Comment by codysoyland** [comment]
Fixed in 5e41226bb03fe80a6c64b78ef70f3d6ede0edeb8
